// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/browse.tsx";
import * as $1 from "./routes/api/chapter.tsx";
import * as $2 from "./routes/api/home.tsx";
import * as $3 from "./routes/api/manga.tsx";
import * as $4 from "./routes/api/search.tsx";
import * as $5 from "./routes/browse.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/library.tsx";
import * as $8 from "./routes/manga/[id].tsx";
import * as $9 from "./routes/manga/[id]/[chapter].tsx";
import * as $10 from "./routes/settings.tsx";

const manifest = {
  routes: {
    "./routes/api/browse.tsx": $0,
    "./routes/api/chapter.tsx": $1,
    "./routes/api/home.tsx": $2,
    "./routes/api/manga.tsx": $3,
    "./routes/api/search.tsx": $4,
    "./routes/browse.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/library.tsx": $7,
    "./routes/manga/[id].tsx": $8,
    "./routes/manga/[id]/[chapter].tsx": $9,
    "./routes/settings.tsx": $10,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
